version: '3.7'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    mem_limit: 256m
  app:
    build: 
        context: .
        dockerfile: Dockerfile.dev
    container_name: schoolmanagement
    image: schoolmanagement:latest
    command: npm run dev
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
    volumes:
      - .:/app
      - node_modules:/app/node_modules
volumes:
  node_modules:

