FROM node:14-alpine

# Set working directory
WORKDIR /app

# Copy package.json and yarn.lock
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the project files
COPY . .

# Build the TypeScript files
RUN npm run build

# Generate Prisma client
RUN npx prisma generate

# Start the application
CMD ["npm", "run", "start"]
